<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью виджета веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Виджет "Блок Яндекс "Поделиться"</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Публикация в своих социальных сетях ссылки на понравившиеся страницы сайта.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('settings') ?>">Настройка виджета</a></li>
    </ul>
</article>